---
- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Check OS system
      block:
      - name: Install pkg
        apt:
         state: present
         name: "{{ item }}"
        with_items: 
         - docker
         - docker-compose
      when:
      - (  ansible_facts['distribution_major_version'] == "22" and  ansible_facts['distribution'] == "Ubuntu" )  or (  ansible_facts['distribution_major_version'] == "12" and  ansible_facts['distribution'] == "Debian"  )
